name: watched

on:
  watch:
    types: [started]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: IFTTT Webhook
      uses: alfredosalzillo/ifttt-webhook-action@v1
      with:
        # IFTTT webhook event
        event: repostarred
        # IFTTT webhook key
        key: ${{ secrets.IFTTT_KEY }}
        # IFTTT webhook optional parameter
        value1: ${{ github.repository }}
        # IFTTT webhook optional parameter
        value2: ${{ github.actor }}
        # IFTTT webhook optional parameter
        # value3: # optional

# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
